// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use chrono::NaiveDateTime;
use diesel::{Queryable, Selectable};
use serde::Serialize;

#[derive(Queryable, Debug, Serialize)]
pub struct Fixture {
    pub id: i32,
    pub home_team: Option<String>,
    pub away_team: Option<String>,
    pub home_score: Option<i32>,
    pub away_score: Option<i32>,
    pub result: Option<i32>,
}

#[derive(Queryable, Selectable, Debug, Serialize)]
pub struct Player {
    pub id: i32,
    pub username: Option<String>,
    pub first_name: Option<String>,
    pub last_name: Option<String>,
    pub email: Option<String>,
    pub is_active: Option<bool>,
    pub points: Option<i32>,
}

#[derive(Queryable, Debug, Serialize)]
pub struct Prediction {
    pub id: i32,
    pub fixture_id: Option<i32>,
    pub player_id: Option<i32>,
    pub home_score: Option<i32>,
    pub away_score: Option<i32>,
    pub result: Option<i32>,
}

#[derive(Queryable, Debug, Serialize)]
pub struct Team {
    pub id: i32,
    pub full_name: Option<String>,
    pub short_name: Option<String>,
    pub three_letter_name: Option<String>,
}

